// source/src/components/Faq.vue
<template>
  <v-container grid-list-md>
    <v-layout row wrap>
      <v-flex xs12>
        <v-card>
          <v-card-title>
            <div class="headline">Frequently Asked Questions</div>
          </v-card-title>
          <v-card-text v-for="faq in faqItems" v-bind:key="faq.Category">
             <h5>{{faq.Category}}</h5>
             <v-expansion-panel>
                <v-expansion-panel-content v-for="qna in faq.Messages" :key="qna.question">
                    <div slot="header">{{qna.question}}</div>
                    <v-card>
                        <v-card-text v-for="answer in qna.answers" :key="answer">
                            <vue-markdown :html="true" :linkify="true" :source="answer"></vue-markdown>
                        </v-card-text>
                    </v-card>
                </v-expansion-panel-content>
             </v-expansion-panel>
          </v-card-text>
        </v-card>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
  import VueMarkdown from 'vue-markdown'

  export default {
    components: {'vue-markdown': VueMarkdown},
    name: 'faq',
    data () {
      return {}
    },
    computed: {
      faqItems: function () {
        return this.$store.state.faqItems.slice(0)
      }
    }
  }

</script>

// source/faq.component.ts
import {Component, OnInit} from "@angular/core";
import {FaqService} from "./_services/faq.service";
import {FaqItem} from "./faq";

@Component({
  selector: 'faq',
  templateUrl: './faq.component.html'
})
export class FaqComponent implements OnInit {
  faqsItems: FaqItem[];

  constructor(private faqService: FaqService) {
  }

  ngOnInit(): void {
    this.faqsItems = this.faqService.getFaqItemsArray();
  }
}

<br/>
<div class="container" fxLayout fxLayout.xs="column" fxLayoutAlign="center" fxLayoutGap="10px" fxLayoutGap.xs="0">
  <div class="item item-1" fxFlex="20%"></div>
  <div class="item item-2" fxFlex="20%" fxFlexOrder="3">
  </div>
  <div class="item item-3" fxFlex>
    <md-card>
      <md-card-header>
        <md-card-title>
          <h3>Frequently Asked Questions</h3>
        </md-card-title>
      </md-card-header>
      <md-card-content>
        <div *ngFor="let faq of faqsItems">
          <md-card-header>
            <h4>{{faq?.Category}}</h4>
          </md-card-header>
          <md-card-content *ngFor="let qna of faq?.Messages">
            <md-expansion-panel>
              <md-expansion-panel-header>
                <mat-panel-description></mat-panel-description>
                <mat-panel-title>{{qna?.question}}</mat-panel-title>
              </md-expansion-panel-header>
              <div *ngFor="let answer of qna?.answers">
                <markdown [data]='answer'></markdown>
              </div>
            </md-expansion-panel>
          </md-card-content>
        </div>
      </md-card-content>
    </md-card>
  </div>
</div>
